version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd src/frontend
      - npm ci
      
  build:
    commands:
      - echo Building React application...
      - |
        cat > .env.production << EOF
        REACT_APP_AWS_REGION=$REACT_APP_AWS_REGION
        REACT_APP_USER_POOL_ID=$REACT_APP_USER_POOL_ID
        REACT_APP_USER_POOL_CLIENT_ID=$REACT_APP_USER_POOL_CLIENT_ID
        REACT_APP_API_ENDPOINT=$REACT_APP_API_ENDPOINT
        EOF
      - npm run build
      - echo Creating deployment package...
      - rm -f deploy.zip
      - zip -r deploy.zip Dockerfile Dockerrun.aws.json nginx.conf build/ package.json
      
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - src/frontend/deploy.zip
  name: frontend-build-$(date +%Y-%m-%d)