name: Trigger AWS CodePipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'terraform/**'
      - '.gitignore'

jobs:
  trigger-pipelines:
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Trigger Frontend Pipeline
      if: success()
      run: |
        echo "Triggering Frontend Pipeline..."
        aws codepipeline start-pipeline-execution \
          --name elearning-dev-frontend-pipeline \
          --region us-east-1

    - name: Trigger ECS Pipeline  
      if: success()
      run: |
        echo "Triggering ECS Pipeline..."
        aws codepipeline start-pipeline-execution \
          --name elearning-dev-ecs-pipeline \
          --region us-east-1

    - name: Pipeline Status
      if: always()
      run: |
        echo "✅ Pipelines triggered successfully!"
        echo "Check the AWS Console for pipeline execution status."